apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: server
          image: uturkarslan/test-go-server-arm:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: OTEL_SERVICE_NAME
              value: "server"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://otelcollector.test.svc.cluster.local:4317"
